/**
 * Test themed signatures on production site
 * Debug why signatures aren't generating
 */

import { test, expect } from '@playwright/test';

const PRODUCTION_URL = 'https://brave-stone-0b7eb4800.3.azurestaticapps.net/themed-signatures.html';

test.describe('Production Themed Signatures Debug', () => {
    test('debug signature generation issues', async ({ page }) => {
        // Enable console logging
        page.on('console', msg => {
            if (msg.type() === 'error') {
                console.log('❌ Console Error:', msg.text());
            } else if (msg.type() === 'warning') {
                console.log('⚠️ Console Warning:', msg.text());
            } else {
                console.log('📝 Console Log:', msg.text());
            }
        });

        // Capture any page errors
        page.on('pageerror', error => {
            console.log('❌ Page Error:', error.message);
        });

        console.log('\n=== TESTING PRODUCTION THEMED SIGNATURES ===');
        console.log('URL:', PRODUCTION_URL);

        // Navigate to the page
        await page.goto(PRODUCTION_URL, {
            waitUntil: 'networkidle',
            timeout: 30000
        });

        // Wait for page to fully load
        await page.waitForTimeout(3000);

        // Check if required elements exist
        const elements = {
            fullName: await page.locator('#fullName').isVisible(),
            jobTitle: await page.locator('#jobTitle').isVisible(),
            email: await page.locator('#email').isVisible(),
            mobile: await page.locator('#mobile').isVisible(),
            generateBtn: await page.locator('#generateBtn').isVisible(),
            previewNew: await page.locator('#previewNew').isVisible(),
            previewReply: await page.locator('#previewReply').isVisible()
        };

        console.log('\n=== ELEMENT VISIBILITY CHECK ===');
        for (const [key, visible] of Object.entries(elements)) {
            console.log(`${key}: ${visible ? '✅' : '❌'}`);
        }

        // Check if theme selector exists
        const themeSelector = await page.locator('#theme-selector-container').isVisible();
        console.log('Theme Selector:', themeSelector ? '✅' : '❌');

        // Check initial values
        const initialValues = {
            fullName: await page.locator('#fullName').inputValue(),
            jobTitle: await page.locator('#jobTitle').inputValue(),
            email: await page.locator('#email').inputValue(),
            mobile: await page.locator('#mobile').inputValue()
        };

        console.log('\n=== INITIAL FORM VALUES ===');
        console.log('Full Name:', initialValues.fullName || '[empty]');
        console.log('Job Title:', initialValues.jobTitle || '[empty]');
        console.log('Email:', initialValues.email || '[empty]');
        console.log('Mobile:', initialValues.mobile || '[empty]');

        // Try filling the form
        console.log('\n=== FILLING FORM ===');
        await page.fill('#fullName', 'Test User');
        console.log('✓ Filled name');

        await page.fill('#jobTitle', 'Test Manager');
        console.log('✓ Filled job title');

        await page.fill('#email', 'test@alterspective.com.au');
        console.log('✓ Filled email');

        await page.fill('#mobile', '0400 123 456');
        console.log('✓ Filled mobile');

        // Wait for auto-generation (if it works)
        console.log('\n=== WAITING FOR AUTO-GENERATION ===');
        await page.waitForTimeout(1000);

        // Check preview content after filling
        let previewContent = await page.locator('#previewNew').innerHTML();
        let hasAutoGenerated = previewContent.includes('<table');
        console.log('Auto-generated after filling:', hasAutoGenerated ? '✅' : '❌');

        if (!hasAutoGenerated) {
            console.log('\n=== TRYING MANUAL GENERATION ===');
            // Try clicking the Generate button
            await page.click('#generateBtn');
            console.log('✓ Clicked Generate button');

            await page.waitForTimeout(1500);

            previewContent = await page.locator('#previewNew').innerHTML();
            let hasGeneratedManual = previewContent.includes('<table');
            console.log('Generated after button click:', hasGeneratedManual ? '✅' : '❌');
        }

        // Check if signatures contain the data
        console.log('\n=== SIGNATURE CONTENT CHECK ===');
        console.log('Contains "Test User":', previewContent.includes('Test User') ? '✅' : '❌');
        console.log('Contains "Test Manager":', previewContent.includes('Test Manager') ? '✅' : '❌');
        console.log('Contains email:', previewContent.includes('test@alterspective.com.au') ? '✅' : '❌');
        console.log('Contains mobile:', previewContent.includes('0400 123 456') ? '✅' : '❌');

        // Check JavaScript functions availability
        console.log('\n=== JAVASCRIPT FUNCTIONS CHECK ===');
        const functions = await page.evaluate(() => {
            return {
                generateThemedSignatures: typeof window.generateThemedSignatures,
                getFormData: typeof window.getFormData,
                isFormValid: typeof window.isFormValid,
                ThemedSignatureGenerator: typeof window.ThemedSignatureGenerator,
                themeManager: typeof window.themeManager,
                signatureGenerator: typeof window.signatureGenerator
            };
        });

        for (const [func, type] of Object.entries(functions)) {
            console.log(`${func}: ${type !== 'undefined' ? '✅' : '❌'} (${type})`);
        }

        // Try changing name to trigger regeneration
        console.log('\n=== TESTING NAME CHANGE ===');
        await page.fill('#fullName', 'Different Name');
        await page.waitForTimeout(1000);

        const newContent = await page.locator('#previewNew').innerHTML();
        const hasUpdated = newContent.includes('Different Name');
        console.log('Updated with new name:', hasUpdated ? '✅' : '❌');

        // Check for any network errors
        console.log('\n=== CHECKING FOR NETWORK ERRORS ===');
        const failedRequests = [];
        page.on('requestfailed', request => {
            failedRequests.push({
                url: request.url(),
                failure: request.failure()
            });
        });

        // Wait a bit to catch any async errors
        await page.waitForTimeout(2000);

        if (failedRequests.length > 0) {
            console.log('Failed requests:');
            failedRequests.forEach(req => {
                console.log(`  ❌ ${req.url}: ${req.failure?.errorText}`);
            });
        } else {
            console.log('✅ No network errors');
        }

        // Take screenshot for debugging
        await page.screenshot({
            path: 'tests/screenshots/production-themed-debug.png',
            fullPage: true
        });
        console.log('\n📸 Screenshot saved: production-themed-debug.png');

        // Final check
        const finalPreview = await page.locator('#previewNew').innerHTML();
        if (finalPreview.includes('<table')) {
            console.log('\n✅ SIGNATURES ARE GENERATING');
        } else {
            console.log('\n❌ SIGNATURES ARE NOT GENERATING');
            console.log('Preview HTML:', finalPreview.substring(0, 200) + '...');
        }
    });
});